version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  lint-and-test:
    docker:
      - image: cimg/node:14.18
    steps:
      - checkout
      - restore_cache:
          name: "Restore Yarn Package Cache"
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: "Install Dependencies"
          command: yarn install --immutable
      - save_cache:
          name: "Save Yarn Package Cache"
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: "JavaScript Linter"
          command: yarn lint
      - run:
          name: "JavaScript Test Suite"
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/junit/
          command: yarn test.jest --ci --runInBand --reporters=default --reporters=jest-junit
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - run:
          name: Build Next.js project
          command: yarn build
      - run:
          name: Start server
          command: yarn start
      - run:
          name: Run e2e tests with Cypress
          command: yarn test.cypress

workflows:
  Lint_And_Test:
    jobs:
      - lint-and-test
