version: 2.1

orbs:
  cypress: cypress-io/cypress@1
  codecov: codecov/codecov@1.2.3
  win: circleci/windows@2.4.1

executors:
  with-chrome-and-firefox:
    docker:
      - image: "cypress/browsers:node14.17.0-chrome88-ff80"
    resource_class: medium+

# ~~~~~~~~~~~~~~~~~~~~~~~ Commands ~~~~~~~~~~~~~~~~~~~~ #
commands:
  report-coverage:
    description: |
      Store coverage report as an artifact and send it to Codecov service.
    steps:
      - store_artifacts:
          path: coverage
      - run: npx nyc report --reporter=text || true
      - codecov/upload:
          file: coverage/coverage-final.json

# ~~~~~~~~~~~~~~ Workflows ~~~~~~~~~~~~~~~~~~~~~~~~~ #
linux-workflow: &linux-workflow
  jobs:
    # Setup
    # 1. Install Cypress and Dependencies
    # 2. Run linter
    # 3. Run unit-tests
    # 4. Run e2e-tests
    - cypress/install:
        name: "Setup Linux"
        yarn: true
        executor: with-chrome-and-firefox
        build: "yarn build"
        post-steps:
          - run:
               name: Print machine info ℹ️
               command: yarn cypress info
          - run:
              name: Lint files
              command: yarn lint
          - run:
              name: Run unit tests
              environment:
                JEST_JUNIT_OUTPUT_DIR: reports/junit/
              command: yarn test.jest --ci --runInBand --reporters=default --reporters=jest-junit

    # Run cypress
    - cypress/run:
        name: "E2E - Chrome - Linux"
        browser: chrome
        spec: cypress/integration/*
        config: "baseUrl=http://localhost:3000"
        environment:
          NODE_ENV: development
        executor: with-chrome-and-firefox
        wait-on: "http://localhost:3000"
        yarn: true
        start: yarn start
        record: true
        parallel: true
        parallelism: 5
        ci-build-id: ${CIRCLE_SHA1:0:8}
        group: "E2E - Chrome"
        requires:
          - Setup Linux
        post-steps:
          - report-coverage

    # Run E2E tests in Firefox
    - cypress/run:
        name: "E2E - Firefox - Linux"
        browser: firefox
        spec: cypress/integration/*
        executor: with-chrome-and-firefox
        wait-on: "http://localhost:3000"
        yarn: true
        start: yarn start
        record: true
        parallel: true
        parallelism: 5
        ci-build-id: ${CIRCLE_SHA1:0:8}
        group: "E2E - Firefox"
        requires:
          - Setup Linux
        post-steps:
          - report-coverage

windows-workflow: &windows-workflow
  jobs:
    # Setup
    # 1. Install Cypress and Dependencies
    # 2. Run linter
    # 3. Run unit-tests
    # 4. Run e2e-tests
    - cypress/install:
        name: "Setup Windows"
        yarn: true
        executor:
          # executor comes from the "windows" orb
          name: win/default
          shell: bash.exe
          size: large
        pre-steps:
          - run:
              name: Disabling Windows Defender
              shell: powershell.exe
              command: Set-MpPreference -DisableRealtimeMonitoring $true
        build: yarn build
        post-steps:
          - run:
               name: Print machine info ℹ️
               command: yarn cypress info
          - run:
              name: Cypress cache list
              command: yarn cypress cache list
          - run:
              name: Lint files
              command: yarn lint
          - run:
              name: Run unit tests
              environment:
                JEST_JUNIT_OUTPUT_DIR: reports/junit/
              command: yarn test.jest --ci --runInBand --reporters=default --reporters=jest-junit

    # Run E2E tests in Windows in Electron
    - cypress/run:
        name: "E2E - Electron - Windows"
        spec: cypress/integration/*
        executor:
          # executor comes from the "windows" orb
          name: win/default
          shell: bash.exe
        wait-on: "http://localhost:3000"
        yarn: true
        start: yarn start
        record: true
        parallel: true
        parallelism: 5
        ci-build-id: ${CIRCLE_SHA1:0:8}
        group: "E2E - Electron - Windows"
        requires:
          - Setup Windows
        post-steps:
          - report-coverage
        no-workspace: true
        timeout: 30m

workflows:
  linux:
    <<: *linux-workflow
  windows:
    <<: *windows-workflow
